targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
           - example/main.dart
        release_options:
          dart2js_args:
            - --fast-startup
            - --minify
            - --omit-implicit-checks
            - --trust-primitives