name: angular_barcode
description: Draw Barcode and QrCode with Angular 2
version: 0.1.0
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/angular_barcode

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  dart_barcode: ^1.0.1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0